 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_snsr.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Karima Mahmoud
 *
 *******************************************************************************/

/*******************************************************************************
 *                           Header Files                                      *
 *******************************************************************************/
#include "gpio.h"
#include "ultrasonic_snsr.h"
#include "icu.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8  g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_distanceCm = 0;

/*******************************************************************************
 *                      Functions Definitions                                   *
 *******************************************************************************/
/*[FUNCTION NAME]	: Ultrasonic_init
 *[DESCRIPTION]		: Initialize the ICU driver as required.
 *                   Setup the ICU call back function.
 *                   Setup the direction for the trigger pin as output pin through the GPIO driver.
 *[ARGUMENTS]		: void
 *[RETURNS]			: void
 */
void Ultrasonic_init(void)
{
	/* Configuration types for ICU initialization */
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};

	/* Initialize ICU driver */
	ICU_init(&ICU_Configurations);

	/* Set call back function for ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup the direction of the Tigger pin/PC0 as output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIG_PIN_PORT_ID,ULTRASONIC_TRIG_PIN_ID,PIN_OUTPUT);
}
/*[FUNCTION NAME]	: Ultrasonic_Trigger
 *[DESCRIPTION]		: Send the Trigger pulse to the ultrasonic.
 *[ARGUMENTS]		: void
 *[RETURNS]			: void
 */
void Ultrasonic_Trigger(void)
{
	/* Set the Trigger pin to high */
	GPIO_writePin(ULTRASONIC_TRIG_PIN_PORT_ID,ULTRASONIC_TRIG_PIN_ID,LOGIC_HIGH);
	/* Wait for 10us */
	_delay_us(10);
	/* Set the Trigger pin to low */
	GPIO_writePin(ULTRASONIC_TRIG_PIN_PORT_ID,ULTRASONIC_TRIG_PIN_ID,LOGIC_LOW);
}
/*[FUNCTION NAME]	: Ultrasonic_readDistance
 *[DESCRIPTION]		: Send the trigger pulse by using Ultrasonic_Trigger function.
 *                    Start the measurements by the ICU from this moment.
 *[ARGUMENTS]		: void
 *[RETURNS]			: uint16 "the measured distance in centimeter"
 */
uint16 Ultrasonic_readDistance(void)
{
	/* Send the trigger pulse by using Ultrasonic_Trigger function */
	Ultrasonic_Trigger();
	return g_distanceCm;
}
/*[FUNCTION NAME]	: Ultrasonic_edgeProcessing
 *[DESCRIPTION]		: This is the call back function called by the ICU driver.
 *                    This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *[ARGUMENTS]		: void
 *[RETURNS]			: void
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/* Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();

		/* Calculate distance */
		g_distanceCm = (g_timeHigh/58);

		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();

		/* Clear edge counter to start measurements again */
		g_edgeCount = 0;

		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}
}
